<?php
declare(strict_types=1);

namespace Database\Seeders;

use App\Models\BaseTraining;
use Illuminate\Database\Seeder;

/**
 * Class BaseTrainingSeeder
 * @package Database\Seeders
 */
class BaseTrainingSeeder extends Seeder
{
    /**
     * @var array|array[] $data
     */
    private array $data = [
        [
            'build_speed' => 0,
            'created_at' => 1704891216,
            'level' => 0,
            'min_base_level' => 0,
            'position_count' => 0,
            'position_price' => 0,
            'power_count' => 0,
            'power_price' => 0,
            'price_buy' => 0,
            'price_sell' => 0,
            'special_count' => 0,
            'special_price' => 0,
            'training_speed_max' => 0,
            'training_speed_min' => 0,
            'updated_at' => 1704891216,
        ],
        [
            'build_speed' => 1,
            'created_at' => 1704891216,
            'level' => 1,
            'min_base_level' => 1,
            'position_count' => 1,
            'position_price' => 50000,
            'power_count' => 5,
            'power_price' => 25000,
            'price_buy' => 250000,
            'price_sell' => 187500,
            'special_count' => 1,
            'special_price' => 50000,
            'training_speed_max' => 15,
            'training_speed_min' => 5,
            'updated_at' => 1704891216,
        ],
        [
            'build_speed' => 2,
            'created_at' => 1704891216,
            'level' => 2,
            'min_base_level' => 1,
            'position_count' => 1,
            'position_price' => 100000,
            'power_count' => 10,
            'power_price' => 50000,
            'price_buy' => 500000,
            'price_sell' => 375000,
            'special_count' => 2,
            'special_price' => 100000,
            'training_speed_max' => 25,
            'training_speed_min' => 15,
            'updated_at' => 1704891216,
        ],
        [
            'build_speed' => 3,
            'created_at' => 1704891216,
            'level' => 3,
            'min_base_level' => 2,
            'position_count' => 2,
            'position_price' => 150000,
            'power_count' => 15,
            'power_price' => 75000,
            'price_buy' => 750000,
            'price_sell' => 562500,
            'special_count' => 3,
            'special_price' => 150000,
            'training_speed_max' => 35,
            'training_speed_min' => 25,
            'updated_at' => 1704891216,
        ],
        [
            'build_speed' => 4,
            'created_at' => 1704891216,
            'level' => 4,
            'min_base_level' => 2,
            'position_count' => 2,
            'position_price' => 200000,
            'power_count' => 20,
            'power_price' => 100000,
            'price_buy' => 1000000,
            'price_sell' => 750000,
            'special_count' => 4,
            'special_price' => 200000,
            'training_speed_max' => 45,
            'training_speed_min' => 35,
            'updated_at' => 1704891216,
        ],
        [
            'build_speed' => 5,
            'created_at' => 1704891216,
            'level' => 5,
            'min_base_level' => 3,
            'position_count' => 3,
            'position_price' => 250000,
            'power_count' => 25,
            'power_price' => 125000,
            'price_buy' => 1250000,
            'price_sell' => 937500,
            'special_count' => 5,
            'special_price' => 250000,
            'training_speed_max' => 55,
            'training_speed_min' => 45,
            'updated_at' => 1704891216,
        ],
        [
            'build_speed' => 6,
            'created_at' => 1704891216,
            'level' => 6,
            'min_base_level' => 3,
            'position_count' => 3,
            'position_price' => 300000,
            'power_count' => 30,
            'power_price' => 150000,
            'price_buy' => 1500000,
            'price_sell' => 1125000,
            'special_count' => 6,
            'special_price' => 300000,
            'training_speed_max' => 65,
            'training_speed_min' => 55,
            'updated_at' => 1704891216,
        ],
        [
            'build_speed' => 7,
            'created_at' => 1704891216,
            'level' => 7,
            'min_base_level' => 4,
            'position_count' => 4,
            'position_price' => 350000,
            'power_count' => 35,
            'power_price' => 175000,
            'price_buy' => 1750000,
            'price_sell' => 1312500,
            'special_count' => 7,
            'special_price' => 350000,
            'training_speed_max' => 75,
            'training_speed_min' => 65,
            'updated_at' => 1704891216,
        ],
        [
            'build_speed' => 8,
            'created_at' => 1704891216,
            'level' => 8,
            'min_base_level' => 4,
            'position_count' => 4,
            'position_price' => 400000,
            'power_count' => 40,
            'power_price' => 200000,
            'price_buy' => 2000000,
            'price_sell' => 1500000,
            'special_count' => 8,
            'special_price' => 400000,
            'training_speed_max' => 85,
            'training_speed_min' => 75,
            'updated_at' => 1704891216,
        ],
        [
            'build_speed' => 9,
            'created_at' => 1704891216,
            'level' => 9,
            'min_base_level' => 5,
            'position_count' => 5,
            'position_price' => 450000,
            'power_count' => 45,
            'power_price' => 225000,
            'price_buy' => 2250000,
            'price_sell' => 1687500,
            'special_count' => 9,
            'special_price' => 450000,
            'training_speed_max' => 95,
            'training_speed_min' => 85,
            'updated_at' => 1704891216,
        ],
        [
            'build_speed' => 10,
            'created_at' => 1704891216,
            'level' => 10,
            'min_base_level' => 5,
            'position_count' => 5,
            'position_price' => 500000,
            'power_count' => 50,
            'power_price' => 250000,
            'price_buy' => 2500000,
            'price_sell' => 1875000,
            'special_count' => 10,
            'special_price' => 500000,
            'training_speed_max' => 100,
            'training_speed_min' => 100,
            'updated_at' => 1704891216,
        ],
    ];

    /**
     * @return void
     */
    public function run(): void
    {
        BaseTraining::insert($this->data);
    }
}
