<?php
declare(strict_types=1);

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

/**
 * Class CitySeeder
 * @package Database\Seeders
 */
class CitySeeder extends Seeder
{
    /**
     * @var string[] $list
     */
    private array $list = [
        ['country_id' => 1, 'name' => 'League'],
        ['country_id' => 8, 'name' => 'Avellaneda'],
        ['country_id' => 8, 'name' => 'Banfield'],
        ['country_id' => 8, 'name' => 'Buenos Aires'],
        ['country_id' => 8, 'name' => 'Carlos Casares'],
        ['country_id' => 8, 'name' => 'Cordoba'],
        ['country_id' => 8, 'name' => 'Florencio Varela'],
        ['country_id' => 8, 'name' => 'Florida Este'],
        ['country_id' => 8, 'name' => 'Godoy Cruz'],
        ['country_id' => 8, 'name' => 'Isidro Casanova'],
        ['country_id' => 8, 'name' => 'Junin'],
        ['country_id' => 8, 'name' => 'La Plata'],
        ['country_id' => 8, 'name' => 'Lanus'],
        ['country_id' => 8, 'name' => 'Rio Cuarto'],
        ['country_id' => 8, 'name' => 'Rosario'],
        ['country_id' => 8, 'name' => 'Santa Fe'],
        ['country_id' => 8, 'name' => 'Santiago del Estero'],
        ['country_id' => 8, 'name' => 'Sarandi'],
        ['country_id' => 8, 'name' => 'Tucuman'],
        ['country_id' => 8, 'name' => 'Victoria'],
        ['country_id' => 18, 'name' => 'Anderlecht'],
        ['country_id' => 18, 'name' => 'Antwerp'],
        ['country_id' => 18, 'name' => 'Beveren'],
        ['country_id' => 18, 'name' => 'Boussu'],
        ['country_id' => 18, 'name' => 'Bruges'],
        ['country_id' => 18, 'name' => 'Charleroi'],
        ['country_id' => 18, 'name' => 'Deinze'],
        ['country_id' => 18, 'name' => 'Denderleeuw'],
        ['country_id' => 18, 'name' => 'Eupen'],
        ['country_id' => 18, 'name' => 'Forest'],
        ['country_id' => 18, 'name' => 'Genk'],
        ['country_id' => 18, 'name' => 'Ghent'],
        ['country_id' => 18, 'name' => 'Kortrijk'],
        ['country_id' => 18, 'name' => 'Leuven'],
        ['country_id' => 18, 'name' => 'Liege'],
        ['country_id' => 18, 'name' => 'Lier'],
        ['country_id' => 18, 'name' => 'Lommel'],
        ['country_id' => 18, 'name' => 'Maasmechelen'],
        ['country_id' => 18, 'name' => 'Mechelen'],
        ['country_id' => 18, 'name' => 'Molenbeek'],
        ['country_id' => 18, 'name' => 'Ostend'],
        ['country_id' => 18, 'name' => 'Seraing'],
        ['country_id' => 18, 'name' => 'Sint-Truiden'],
        ['country_id' => 18, 'name' => 'Waregem'],
        ['country_id' => 18, 'name' => 'Westerlo'],
        ['country_id' => 25, 'name' => 'Belo Horizonte'],
        ['country_id' => 25, 'name' => 'Braganca Paulista'],
        ['country_id' => 25, 'name' => 'Campinas'],
        ['country_id' => 25, 'name' => 'Caxias do Sul'],
        ['country_id' => 25, 'name' => 'Criciuma'],
        ['country_id' => 25, 'name' => 'Cuiaba'],
        ['country_id' => 25, 'name' => 'Curitiba'],
        ['country_id' => 25, 'name' => 'Fortaleza'],
        ['country_id' => 25, 'name' => 'Goiania'],
        ['country_id' => 25, 'name' => 'Maceio'],
        ['country_id' => 25, 'name' => 'Mirassol'],
        ['country_id' => 25, 'name' => 'Novo Horizonte'],
        ['country_id' => 25, 'name' => 'Porto Alegre'],
        ['country_id' => 25, 'name' => 'Recife'],
        ['country_id' => 25, 'name' => 'Ribeirao Preto'],
        ['country_id' => 25, 'name' => 'Rio de Janeiro'],
        ['country_id' => 25, 'name' => 'Salvador'],
        ['country_id' => 25, 'name' => 'Santos'],
        ['country_id' => 25, 'name' => 'Sao Paulo'],
        ['country_id' => 55, 'name' => 'Birmingham'],
        ['country_id' => 55, 'name' => 'Bournemouth'],
        ['country_id' => 55, 'name' => 'Brighton'],
        ['country_id' => 55, 'name' => 'Bristol'],
        ['country_id' => 55, 'name' => 'Burnley'],
        ['country_id' => 55, 'name' => 'Coventry'],
        ['country_id' => 55, 'name' => 'Hull'],
        ['country_id' => 55, 'name' => 'Ipswich'],
        ['country_id' => 55, 'name' => 'Leeds'],
        ['country_id' => 55, 'name' => 'Leicester'],
        ['country_id' => 55, 'name' => 'Liverpool'],
        ['country_id' => 55, 'name' => 'London'],
        ['country_id' => 55, 'name' => 'Luton'],
        ['country_id' => 55, 'name' => 'Manchester'],
        ['country_id' => 55, 'name' => 'Middlesbrough'],
        ['country_id' => 55, 'name' => 'Newcastle'],
        ['country_id' => 55, 'name' => 'Norwich'],
        ['country_id' => 55, 'name' => 'Sheffield'],
        ['country_id' => 55, 'name' => 'Southampton'],
        ['country_id' => 55, 'name' => 'Sunderland'],
        ['country_id' => 55, 'name' => 'Watford'],
        ['country_id' => 55, 'name' => 'West Bridgford'],
        ['country_id' => 55, 'name' => 'West Bromwich'],
        ['country_id' => 55, 'name' => 'Wolverhampton'],
        ['country_id' => 63, 'name' => 'Ajaccio'],
        ['country_id' => 63, 'name' => 'Amiens'],
        ['country_id' => 63, 'name' => 'Angers'],
        ['country_id' => 63, 'name' => 'Auxerre'],
        ['country_id' => 63, 'name' => 'Bordeaux'],
        ['country_id' => 63, 'name' => 'Brest'],
        ['country_id' => 63, 'name' => 'Caen'],
        ['country_id' => 63, 'name' => 'Clermont-Ferrand'],
        ['country_id' => 63, 'name' => 'Concarneau'],
        ['country_id' => 63, 'name' => 'Grenoble'],
        ['country_id' => 63, 'name' => 'Guingamp'],
        ['country_id' => 63, 'name' => 'Laval'],
        ['country_id' => 63, 'name' => 'Le Havre'],
        ['country_id' => 63, 'name' => 'Lens'],
        ['country_id' => 63, 'name' => 'Lille'],
        ['country_id' => 63, 'name' => 'Longeville-les-Metz'],
        ['country_id' => 63, 'name' => 'Lorient'],
        ['country_id' => 63, 'name' => 'Lyon'],
        ['country_id' => 63, 'name' => 'Marseille'],
        ['country_id' => 63, 'name' => 'Monaco'],
        ['country_id' => 63, 'name' => 'Montpellier'],
        ['country_id' => 63, 'name' => 'Nantes'],
        ['country_id' => 63, 'name' => 'Nice'],
        ['country_id' => 63, 'name' => 'Paris'],
        ['country_id' => 63, 'name' => 'Pau'],
        ['country_id' => 63, 'name' => 'Reims'],
        ['country_id' => 63, 'name' => 'Rennes'],
        ['country_id' => 63, 'name' => 'Rodez'],
        ['country_id' => 63, 'name' => 'Saint-Etienne'],
        ['country_id' => 63, 'name' => 'Strasbourg'],
        ['country_id' => 63, 'name' => 'Toulouse'],
        ['country_id' => 67, 'name' => 'Augsburg'],
        ['country_id' => 67, 'name' => 'Berlin'],
        ['country_id' => 67, 'name' => 'Bochum'],
        ['country_id' => 67, 'name' => 'Bremen'],
        ['country_id' => 67, 'name' => 'Cologne'],
        ['country_id' => 67, 'name' => 'Darmstadt'],
        ['country_id' => 67, 'name' => 'Dortmund'],
        ['country_id' => 67, 'name' => 'Dusseldorf'],
        ['country_id' => 67, 'name' => 'Frankfurt'],
        ['country_id' => 67, 'name' => 'Freiburg im Breisgau'],
        ['country_id' => 67, 'name' => 'Furth'],
        ['country_id' => 67, 'name' => 'Gelsenkirchen'],
        ['country_id' => 67, 'name' => 'Hamburg'],
        ['country_id' => 67, 'name' => 'Hanover'],
        ['country_id' => 67, 'name' => 'Heidenheim'],
        ['country_id' => 67, 'name' => 'Karlsruhe'],
        ['country_id' => 67, 'name' => 'Kiel'],
        ['country_id' => 67, 'name' => 'Leipzig'],
        ['country_id' => 67, 'name' => 'Leverkusen'],
        ['country_id' => 67, 'name' => 'Magdeburg'],
        ['country_id' => 67, 'name' => 'Mainz'],
        ['country_id' => 67, 'name' => 'Monchengladbach'],
        ['country_id' => 67, 'name' => 'Munich'],
        ['country_id' => 67, 'name' => 'Nuremberg'],
        ['country_id' => 67, 'name' => 'Paderborn'],
        ['country_id' => 67, 'name' => 'Sinsheim'],
        ['country_id' => 67, 'name' => 'Spiesen-Elversberg'],
        ['country_id' => 67, 'name' => 'Stuttgart'],
        ['country_id' => 67, 'name' => 'Wiesbaden'],
        ['country_id' => 67, 'name' => 'Wolfsburg'],
        ['country_id' => 86, 'name' => 'Bari'],
        ['country_id' => 86, 'name' => 'Bergamo'],
        ['country_id' => 86, 'name' => 'Bologna'],
        ['country_id' => 86, 'name' => 'Bolzano'],
        ['country_id' => 86, 'name' => 'Brescia'],
        ['country_id' => 86, 'name' => 'Cagliari'],
        ['country_id' => 86, 'name' => 'Catanzaro'],
        ['country_id' => 86, 'name' => 'Cittadella'],
        ['country_id' => 86, 'name' => 'Como'],
        ['country_id' => 86, 'name' => 'Cremona'],
        ['country_id' => 86, 'name' => 'Empoli'],
        ['country_id' => 86, 'name' => 'Florence'],
        ['country_id' => 86, 'name' => 'Frosinone'],
        ['country_id' => 86, 'name' => 'Genoa'],
        ['country_id' => 86, 'name' => 'Lecce'],
        ['country_id' => 86, 'name' => 'Milan'],
        ['country_id' => 86, 'name' => 'Modena'],
        ['country_id' => 86, 'name' => 'Monza'],
        ['country_id' => 86, 'name' => 'Naples'],
        ['country_id' => 86, 'name' => 'Palermo'],
        ['country_id' => 86, 'name' => 'Parma'],
        ['country_id' => 86, 'name' => 'Rome'],
        ['country_id' => 86, 'name' => 'Salerno'],
        ['country_id' => 86, 'name' => 'Sassuolo'],
        ['country_id' => 86, 'name' => 'Turin'],
        ['country_id' => 86, 'name' => 'Udine'],
        ['country_id' => 86, 'name' => 'Venice'],
        ['country_id' => 86, 'name' => 'Verona'],
        ['country_id' => 125, 'name' => 'Alkmaar'],
        ['country_id' => 125, 'name' => 'Almelo'],
        ['country_id' => 125, 'name' => 'Almere'],
        ['country_id' => 125, 'name' => 'Amsterdam'],
        ['country_id' => 125, 'name' => 'Arnhem'],
        ['country_id' => 125, 'name' => 'Breda'],
        ['country_id' => 125, 'name' => 'Deventer'],
        ['country_id' => 125, 'name' => 'Doetinchem'],
        ['country_id' => 125, 'name' => 'Dordrecht'],
        ['country_id' => 125, 'name' => 'Eindhoven'],
        ['country_id' => 125, 'name' => 'Emmen'],
        ['country_id' => 125, 'name' => 'Enschede'],
        ['country_id' => 125, 'name' => 'Groningen'],
        ['country_id' => 125, 'name' => 'Heerenveen'],
        ['country_id' => 125, 'name' => 'Helmond'],
        ['country_id' => 125, 'name' => 'Hertogenbosch'],
        ['country_id' => 125, 'name' => 'Kerkrade'],
        ['country_id' => 125, 'name' => 'Leeuwarden'],
        ['country_id' => 125, 'name' => 'Maastricht'],
        ['country_id' => 125, 'name' => 'Nijmegen'],
        ['country_id' => 125, 'name' => 'Rotterdam'],
        ['country_id' => 125, 'name' => 'Sittard'],
        ['country_id' => 125, 'name' => 'The Hague'],
        ['country_id' => 125, 'name' => 'Tilburg'],
        ['country_id' => 125, 'name' => 'Utrecht'],
        ['country_id' => 125, 'name' => 'Venlo'],
        ['country_id' => 125, 'name' => 'Volendam'],
        ['country_id' => 125, 'name' => 'Waalwijk'],
        ['country_id' => 125, 'name' => 'Zwolle'],
        ['country_id' => 144, 'name' => 'Amadora'],
        ['country_id' => 144, 'name' => 'Arouca'],
        ['country_id' => 144, 'name' => 'Barcelos'],
        ['country_id' => 144, 'name' => 'Braga'],
        ['country_id' => 144, 'name' => 'Chaves'],
        ['country_id' => 144, 'name' => 'Estoril'],
        ['country_id' => 144, 'name' => 'Faro'],
        ['country_id' => 144, 'name' => 'Funchal'],
        ['country_id' => 144, 'name' => 'Guimaraes'],
        ['country_id' => 144, 'name' => 'Leiria'],
        ['country_id' => 144, 'name' => 'Lisbon'],
        ['country_id' => 144, 'name' => 'Mafra'],
        ['country_id' => 144, 'name' => 'Moreira de Conegos'],
        ['country_id' => 144, 'name' => 'Oliveira de Azemeis'],
        ['country_id' => 144, 'name' => 'Pacos de Ferreira'],
        ['country_id' => 144, 'name' => 'Ponta Delgada'],
        ['country_id' => 144, 'name' => 'Portimao'],
        ['country_id' => 144, 'name' => 'Porto'],
        ['country_id' => 144, 'name' => 'Santa Maria da Feira'],
        ['country_id' => 144, 'name' => 'Seixal'],
        ['country_id' => 144, 'name' => 'Tondela'],
        ['country_id' => 144, 'name' => 'Torres Vedras'],
        ['country_id' => 144, 'name' => 'Vila das Aves'],
        ['country_id' => 144, 'name' => 'Vila do Conde'],
        ['country_id' => 144, 'name' => 'Vila Nova de Famalicao'],
        ['country_id' => 144, 'name' => 'Vila Nova de Gaia'],
        ['country_id' => 144, 'name' => 'Viseu'],
        ['country_id' => 144, 'name' => 'Vizela'],
        ['country_id' => 169, 'name' => 'Almeria'],
        ['country_id' => 169, 'name' => 'Barcelona'],
        ['country_id' => 169, 'name' => 'Bilbao'],
        ['country_id' => 169, 'name' => 'Burgos'],
        ['country_id' => 169, 'name' => 'Cadiz'],
        ['country_id' => 169, 'name' => 'Cornella de Llobregat'],
        ['country_id' => 169, 'name' => 'Eibar'],
        ['country_id' => 169, 'name' => 'Elche'],
        ['country_id' => 169, 'name' => 'Ferrol'],
        ['country_id' => 169, 'name' => 'Getafe'],
        ['country_id' => 169, 'name' => 'Gijon'],
        ['country_id' => 169, 'name' => 'Girona'],
        ['country_id' => 169, 'name' => 'Granada'],
        ['country_id' => 169, 'name' => 'Las Palmas'],
        ['country_id' => 169, 'name' => 'Leganes'],
        ['country_id' => 169, 'name' => 'Madrid'],
        ['country_id' => 169, 'name' => 'Oviedo'],
        ['country_id' => 169, 'name' => 'Palma'],
        ['country_id' => 169, 'name' => 'Pamplona'],
        ['country_id' => 169, 'name' => 'San Sebastian'],
        ['country_id' => 169, 'name' => 'Santa Cruz de Tenerife'],
        ['country_id' => 169, 'name' => 'Santander'],
        ['country_id' => 169, 'name' => 'Seville'],
        ['country_id' => 169, 'name' => 'Valencia'],
        ['country_id' => 169, 'name' => 'Valladolid'],
        ['country_id' => 169, 'name' => 'Vigo'],
        ['country_id' => 169, 'name' => 'Villarreal'],
        ['country_id' => 169, 'name' => 'Vitoria-Gasteiz'],
    ];


    /**
     * @return void
     */
    public function run(): void
    {
        foreach ($this->list as $item) {
            City::create(['country_id' => $item['country_id'], 'name' => $item['name']]);
        }
    }
}
