<?php
declare(strict_types=1);

namespace Database\Seeders;

use App\Models\CountryName;
use Illuminate\Database\Seeder;

/**
 * Class CountryNameSeeder
 * @package Database\Seeders
 */
class CountryNameSeeder extends Seeder
{
    /**
     * @var string[] $list
     */
    private array $list = [
        ['country_id' => 8, 'name_id' => 16],
        ['country_id' => 8, 'name_id' => 17],
        ['country_id' => 8, 'name_id' => 19],
        ['country_id' => 8, 'name_id' => 20],
        ['country_id' => 8, 'name_id' => 24],
        ['country_id' => 8, 'name_id' => 26],
        ['country_id' => 8, 'name_id' => 29],
        ['country_id' => 8, 'name_id' => 41],
        ['country_id' => 8, 'name_id' => 46],
        ['country_id' => 8, 'name_id' => 62],
        ['country_id' => 8, 'name_id' => 71],
        ['country_id' => 8, 'name_id' => 73],
        ['country_id' => 8, 'name_id' => 79],
        ['country_id' => 8, 'name_id' => 80],
        ['country_id' => 8, 'name_id' => 94],
        ['country_id' => 8, 'name_id' => 105],
        ['country_id' => 8, 'name_id' => 124],
        ['country_id' => 8, 'name_id' => 125],
        ['country_id' => 8, 'name_id' => 129],
        ['country_id' => 8, 'name_id' => 133],
        ['country_id' => 18, 'name_id' => 2],
        ['country_id' => 18, 'name_id' => 15],
        ['country_id' => 18, 'name_id' => 44],
        ['country_id' => 18, 'name_id' => 49],
        ['country_id' => 18, 'name_id' => 72],
        ['country_id' => 18, 'name_id' => 75],
        ['country_id' => 18, 'name_id' => 78],
        ['country_id' => 18, 'name_id' => 79],
        ['country_id' => 18, 'name_id' => 81],
        ['country_id' => 18, 'name_id' => 83],
        ['country_id' => 18, 'name_id' => 84],
        ['country_id' => 18, 'name_id' => 96],
        ['country_id' => 18, 'name_id' => 97],
        ['country_id' => 18, 'name_id' => 102],
        ['country_id' => 18, 'name_id' => 105],
        ['country_id' => 18, 'name_id' => 109],
        ['country_id' => 18, 'name_id' => 115],
        ['country_id' => 18, 'name_id' => 117],
        ['country_id' => 18, 'name_id' => 127],
        ['country_id' => 18, 'name_id' => 135],
        ['country_id' => 25, 'name_id' => 11],
        ['country_id' => 25, 'name_id' => 15],
        ['country_id' => 25, 'name_id' => 19],
        ['country_id' => 25, 'name_id' => 21],
        ['country_id' => 25, 'name_id' => 30],
        ['country_id' => 25, 'name_id' => 49],
        ['country_id' => 25, 'name_id' => 51],
        ['country_id' => 25, 'name_id' => 58],
        ['country_id' => 25, 'name_id' => 59],
        ['country_id' => 25, 'name_id' => 63],
        ['country_id' => 25, 'name_id' => 69],
        ['country_id' => 25, 'name_id' => 77],
        ['country_id' => 25, 'name_id' => 80],
        ['country_id' => 25, 'name_id' => 84],
        ['country_id' => 25, 'name_id' => 100],
        ['country_id' => 25, 'name_id' => 105],
        ['country_id' => 25, 'name_id' => 113],
        ['country_id' => 25, 'name_id' => 116],
        ['country_id' => 25, 'name_id' => 122],
        ['country_id' => 25, 'name_id' => 127],
        ['country_id' => 55, 'name_id' => 8],
        ['country_id' => 55, 'name_id' => 13],
        ['country_id' => 55, 'name_id' => 14],
        ['country_id' => 55, 'name_id' => 15],
        ['country_id' => 55, 'name_id' => 25],
        ['country_id' => 55, 'name_id' => 43],
        ['country_id' => 55, 'name_id' => 47],
        ['country_id' => 55, 'name_id' => 52],
        ['country_id' => 55, 'name_id' => 57],
        ['country_id' => 55, 'name_id' => 60],
        ['country_id' => 55, 'name_id' => 64],
        ['country_id' => 55, 'name_id' => 65],
        ['country_id' => 55, 'name_id' => 74],
        ['country_id' => 55, 'name_id' => 105],
        ['country_id' => 55, 'name_id' => 108],
        ['country_id' => 55, 'name_id' => 109],
        ['country_id' => 55, 'name_id' => 127],
        ['country_id' => 55, 'name_id' => 128],
        ['country_id' => 55, 'name_id' => 130],
        ['country_id' => 55, 'name_id' => 136],
        ['country_id' => 63, 'name_id' => 1],
        ['country_id' => 63, 'name_id' => 2],
        ['country_id' => 63, 'name_id' => 15],
        ['country_id' => 63, 'name_id' => 34],
        ['country_id' => 63, 'name_id' => 48],
        ['country_id' => 63, 'name_id' => 49],
        ['country_id' => 63, 'name_id' => 61],
        ['country_id' => 63, 'name_id' => 72],
        ['country_id' => 63, 'name_id' => 74],
        ['country_id' => 63, 'name_id' => 75],
        ['country_id' => 63, 'name_id' => 79],
        ['country_id' => 63, 'name_id' => 81],
        ['country_id' => 63, 'name_id' => 84],
        ['country_id' => 63, 'name_id' => 87],
        ['country_id' => 63, 'name_id' => 89],
        ['country_id' => 63, 'name_id' => 103],
        ['country_id' => 63, 'name_id' => 105],
        ['country_id' => 63, 'name_id' => 106],
        ['country_id' => 63, 'name_id' => 112],
        ['country_id' => 63, 'name_id' => 115],
        ['country_id' => 67, 'name_id' => 18],
        ['country_id' => 67, 'name_id' => 36],
        ['country_id' => 67, 'name_id' => 37],
        ['country_id' => 67, 'name_id' => 42],
        ['country_id' => 67, 'name_id' => 44],
        ['country_id' => 67, 'name_id' => 60],
        ['country_id' => 67, 'name_id' => 66],
        ['country_id' => 67, 'name_id' => 70],
        ['country_id' => 67, 'name_id' => 74],
        ['country_id' => 67, 'name_id' => 75],
        ['country_id' => 67, 'name_id' => 77],
        ['country_id' => 67, 'name_id' => 79],
        ['country_id' => 67, 'name_id' => 81],
        ['country_id' => 67, 'name_id' => 83],
        ['country_id' => 67, 'name_id' => 85],
        ['country_id' => 67, 'name_id' => 97],
        ['country_id' => 67, 'name_id' => 105],
        ['country_id' => 67, 'name_id' => 110],
        ['country_id' => 67, 'name_id' => 112],
        ['country_id' => 67, 'name_id' => 127],
        ['country_id' => 86, 'name_id' => 6],
        ['country_id' => 86, 'name_id' => 10],
        ['country_id' => 86, 'name_id' => 12],
        ['country_id' => 86, 'name_id' => 32],
        ['country_id' => 86, 'name_id' => 35],
        ['country_id' => 86, 'name_id' => 38],
        ['country_id' => 86, 'name_id' => 40],
        ['country_id' => 86, 'name_id' => 45],
        ['country_id' => 86, 'name_id' => 50],
        ['country_id' => 86, 'name_id' => 53],
        ['country_id' => 86, 'name_id' => 54],
        ['country_id' => 86, 'name_id' => 76],
        ['country_id' => 86, 'name_id' => 80],
        ['country_id' => 86, 'name_id' => 97],
        ['country_id' => 86, 'name_id' => 98],
        ['country_id' => 86, 'name_id' => 104],
        ['country_id' => 86, 'name_id' => 114],
        ['country_id' => 86, 'name_id' => 118],
        ['country_id' => 86, 'name_id' => 123],
        ['country_id' => 86, 'name_id' => 132],
        ['country_id' => 125, 'name_id' => 2],
        ['country_id' => 125, 'name_id' => 20],
        ['country_id' => 125, 'name_id' => 22],
        ['country_id' => 125, 'name_id' => 23],
        ['country_id' => 125, 'name_id' => 27],
        ['country_id' => 125, 'name_id' => 44],
        ['country_id' => 125, 'name_id' => 67],
        ['country_id' => 125, 'name_id' => 77],
        ['country_id' => 125, 'name_id' => 79],
        ['country_id' => 125, 'name_id' => 83],
        ['country_id' => 125, 'name_id' => 84],
        ['country_id' => 125, 'name_id' => 86],
        ['country_id' => 125, 'name_id' => 93],
        ['country_id' => 125, 'name_id' => 99],
        ['country_id' => 125, 'name_id' => 101],
        ['country_id' => 125, 'name_id' => 105],
        ['country_id' => 125, 'name_id' => 107],
        ['country_id' => 125, 'name_id' => 121],
        ['country_id' => 125, 'name_id' => 126],
        ['country_id' => 125, 'name_id' => 137],
        ['country_id' => 144, 'name_id' => 4],
        ['country_id' => 144, 'name_id' => 21],
        ['country_id' => 144, 'name_id' => 33],
        ['country_id' => 144, 'name_id' => 46],
        ['country_id' => 144, 'name_id' => 49],
        ['country_id' => 144, 'name_id' => 55],
        ['country_id' => 144, 'name_id' => 56],
        ['country_id' => 144, 'name_id' => 68],
        ['country_id' => 144, 'name_id' => 82],
        ['country_id' => 144, 'name_id' => 84],
        ['country_id' => 144, 'name_id' => 88],
        ['country_id' => 144, 'name_id' => 91],
        ['country_id' => 144, 'name_id' => 95],
        ['country_id' => 144, 'name_id' => 100],
        ['country_id' => 144, 'name_id' => 113],
        ['country_id' => 144, 'name_id' => 119],
        ['country_id' => 144, 'name_id' => 120],
        ['country_id' => 144, 'name_id' => 124],
        ['country_id' => 144, 'name_id' => 131],
        ['country_id' => 144, 'name_id' => 134],
        ['country_id' => 169, 'name_id' => 3],
        ['country_id' => 169, 'name_id' => 5],
        ['country_id' => 169, 'name_id' => 7],
        ['country_id' => 169, 'name_id' => 9],
        ['country_id' => 169, 'name_id' => 24],
        ['country_id' => 169, 'name_id' => 28],
        ['country_id' => 169, 'name_id' => 31],
        ['country_id' => 169, 'name_id' => 32],
        ['country_id' => 169, 'name_id' => 39],
        ['country_id' => 169, 'name_id' => 61],
        ['country_id' => 169, 'name_id' => 74],
        ['country_id' => 169, 'name_id' => 83],
        ['country_id' => 169, 'name_id' => 84],
        ['country_id' => 169, 'name_id' => 88],
        ['country_id' => 169, 'name_id' => 90],
        ['country_id' => 169, 'name_id' => 92],
        ['country_id' => 169, 'name_id' => 94],
        ['country_id' => 169, 'name_id' => 108],
        ['country_id' => 169, 'name_id' => 111],
        ['country_id' => 169, 'name_id' => 129],
    ];

    /**
     * @return void
     */
    public function run(): void
    {
        foreach ($this->list as $item) {
            CountryName::create(['country_id' => $item['country_id'], 'name_id' => $item['name_id']]);
        }
    }
}
