<?php
declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Name;
use Illuminate\Database\Seeder;

/**
 * Class NameSeeder
 * @package Database\Seeders
 */
class NameSeeder extends Seeder
{
    /**
     * @var string[] $list
     */
    private array $list = [
        'Aaron',
        'Adam',
        'Adrian',
        'Afonso',
        'Alejandro',
        'Alessandro',
        'Alex',
        'Alfie',
        'Alvaro',
        'Andrea',
        'Anthony',
        'Antonio',
        'Archie',
        'Arlo',
        'Arthur',
        'Bastian',
        'Bautista',
        'Ben',
        'Benicio',
        'Benjamin',
        'Bernardo',
        'Boaz',
        'Bram',
        'Bruno',
        'Charlie',
        'Ciro',
        'Daan',
        'Daniel',
        'Dante',
        'Davi',
        'David',
        'Diego',
        'Duarte',
        'Eden',
        'Edoardo',
        'Elias',
        'Emil',
        'Enea',
        'Enzo',
        'Federico',
        'Felipe',
        'Felix',
        'Finley',
        'Finn',
        'Francesco',
        'Francisco',
        'Freddie',
        'Gabin',
        'Gabriel',
        'Gabriele',
        'Gael',
        'George',
        'Giovanni',
        'Giuseppe',
        'Goncalo',
        'Guilherme',
        'Harry',
        'Heitor',
        'Henrique',
        'Henry',
        'Hugo',
        'Ignacio',
        'Isaac',
        'Jack',
        'Jacob',
        'Jakob',
        'James',
        'Joao',
        'Joaquim',
        'Jonas',
        'Juan',
        'Jules',
        'Lautaro',
        'Leo',
        'Leon',
        'Leonardo',
        'Levi',
        'Lewis',
        'Liam',
        'Lorenzo',
        'Louis',
        'Lourenco',
        'Luca',
        'Lucas',
        'Lukas',
        'Luuk',
        'Mael',
        'Manuel',
        'Marceau',
        'Mario',
        'Martim',
        'Martin',
        'Mason',
        'Mateo',
        'Mateus',
        'Mathis',
        'Matteo',
        'Mattia',
        'Mees',
        'Miguel',
        'Milan',
        'Mohamed',
        'Nael',
        'Nicolo',
        'Noah',
        'Noe',
        'Noud',
        'Oliver',
        'Oscar',
        'Oskar',
        'Pablo',
        'Paul',
        'Pedro',
        'Pietro',
        'Raphael',
        'Ravi',
        'Rayan',
        'Riccardo',
        'Rodrigo',
        'Salvador',
        'Sam',
        'Samuel',
        'Samuele',
        'Santiago',
        'Santino',
        'Sem',
        'Theo',
        'Theodore',
        'Thiago',
        'Thomas',
        'Tomas',
        'Tommaso',
        'Valentino',
        'Vicente',
        'Victor',
        'William',
        'Zayn',
    ];

    /**
     * @return void
     */
    public function run(): void
    {
        foreach ($this->list as $name) {
            Name::create(['name' => $name]);
        }
    }
}
