<?php
declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Stadium;
use Illuminate\Database\Seeder;

/**
 * Class StadiumSeeder
 * @package Database\Seeders
 */
class StadiumSeeder extends Seeder
{
    /**
     * @var string[] $list
     */
    private array $list = [
        ['city_id' => 1, 'name' => 'League'],
        ['city_id' => 4, 'name' => 'Mas Monumental'],
        ['city_id' => 6, 'name' => 'Mario Alberto Kempes'],
        ['city_id' => 15, 'name' => 'Gigante de Arroyito'],
        ['city_id' => 4, 'name' => 'Pedro Bidegain'],
        ['city_id' => 9, 'name' => 'Malvinas Argentinas'],
        ['city_id' => 4, 'name' => 'Alberto J Armando'],
        ['city_id' => 12, 'name' => 'Jorge Luis Hirschi'],
        ['city_id' => 2, 'name' => 'Presidente Peron'],
        ['city_id' => 7, 'name' => 'Norberto Tomaghello'],
        ['city_id' => 13, 'name' => 'Ciudad de Lanus'],
        ['city_id' => 6, 'name' => 'Julio Cesar Villagra'],
        ['city_id' => 4, 'name' => 'Diego Armando Maradona'],
        ['city_id' => 19, 'name' => 'Monumental Jose Fierro'],
        ['city_id' => 8, 'name' => 'Ciudad de Vicente Lopez'],
        ['city_id' => 15, 'name' => 'Marcelo Bielsa'],
        ['city_id' => 3, 'name' => 'Florencio Sola'],
        ['city_id' => 6, 'name' => 'Presidente Peron'],
        ['city_id' => 4, 'name' => 'Tomas Adolfo Duco'],
        ['city_id' => 2, 'name' => 'Libertadores de America'],
        ['city_id' => 4, 'name' => 'Jose Amalfitani'],
        ['city_id' => 4, 'name' => 'Claudio Tapia'],
        ['city_id' => 17, 'name' => 'Unico Madre de Ciudades'],
        ['city_id' => 20, 'name' => 'Jose Dellagiovanna'],
        ['city_id' => 11, 'name' => 'Eva Peron'],
        ['city_id' => 16, 'name' => '15 de Abril'],
        ['city_id' => 16, 'name' => 'Brigadier General Estanislao Lopez'],
        ['city_id' => 12, 'name' => 'Juan Carmelo Zerillo'],
        ['city_id' => 18, 'name' => 'Julio Humberto Grondona'],
        ['city_id' => 10, 'name' => 'Fragata Presidente Sarmiento'],
        ['city_id' => 5, 'name' => 'Ofelia Rosenzuaig'],
        ['city_id' => 19, 'name' => 'La Ciudadela'],
        ['city_id' => 14, 'name' => 'Antonio Candini'],
        ['city_id' => 21, 'name' => 'Constant Vanden Stock Stadium'],
        ['city_id' => 22, 'name' => 'Bosuilstadion'],
        ['city_id' => 25, 'name' => 'Jan Breydel Stadium'],
        ['city_id' => 26, 'name' => 'Stade du Pays de Charleroi'],
        ['city_id' => 25, 'name' => 'Jan Breydel Stadium'],
        ['city_id' => 29, 'name' => 'Kehrwegstadion'],
        ['city_id' => 31, 'name' => 'Cegeka Arena'],
        ['city_id' => 32, 'name' => 'Ghelamco Arena'],
        ['city_id' => 33, 'name' => 'Guldensporen Stadion'],
        ['city_id' => 39, 'name' => 'Achter de Kazerne'],
        ['city_id' => 34, 'name' => 'Den Dreef'],
        ['city_id' => 40, 'name' => 'Edmond Machtens Stadium'],
        ['city_id' => 43, 'name' => 'Stayen'],
        ['city_id' => 35, 'name' => 'Stade Maurice Dufrasne'],
        ['city_id' => 30, 'name' => 'Stade Joseph Marien'],
        ['city_id' => 45, 'name' => 'Het Kuipje'],
        ['city_id' => 21, 'name' => 'King Baudouin Stadium'],
        ['city_id' => 22, 'name' => 'Olympic Stadium'],
        ['city_id' => 23, 'name' => 'Freethiel Stadion'],
        ['city_id' => 25, 'name' => 'Schiervelde Stadion'],
        ['city_id' => 27, 'name' => 'Burgemeester Van de Wiele Stadion'],
        ['city_id' => 28, 'name' => 'Van Roystadion'],
        ['city_id' => 24, 'name' => 'Stade Robert Urbain'],
        ['city_id' => 31, 'name' => 'Luminus Arena'],
        ['city_id' => 36, 'name' => 'Herman Vanderpoortenstadion'],
        ['city_id' => 37, 'name' => 'Soevereinstadion'],
        ['city_id' => 41, 'name' => 'Diaz Arena'],
        ['city_id' => 38, 'name' => 'Gemeentelijk Sportparkstadion'],
        ['city_id' => 35, 'name' => 'Stade de Rocourt'],
        ['city_id' => 42, 'name' => 'Stade du Pairay'],
        ['city_id' => 35, 'name' => 'Stade Maurice Dufrasne'],
        ['city_id' => 44, 'name' => 'Regenboogstadion'],
        ['city_id' => 46, 'name' => 'Independencia'],
        ['city_id' => 52, 'name' => 'Ligga Arena'],
        ['city_id' => 46, 'name' => 'Arena MRV'],
        ['city_id' => 62, 'name' => 'Itaipava Arena Fonte Nova'],
        ['city_id' => 61, 'name' => 'Olimpico Nilton Santos'],
        ['city_id' => 64, 'name' => 'Neo Quimica Arena'],
        ['city_id' => 52, 'name' => 'Couto Pereira'],
        ['city_id' => 46, 'name' => 'Mineirao'],
        ['city_id' => 51, 'name' => 'Arena Pantanal'],
        ['city_id' => 61, 'name' => 'Maracana'],
        ['city_id' => 61, 'name' => 'Maracana'],
        ['city_id' => 53, 'name' => 'Castelao'],
        ['city_id' => 54, 'name' => 'Serrinha'],
        ['city_id' => 58, 'name' => 'Arena do Gremio'],
        ['city_id' => 58, 'name' => 'Beira-Rio'],
        ['city_id' => 64, 'name' => 'Allianz Parque'],
        ['city_id' => 47, 'name' => 'Nabi Abi Chedid'],
        ['city_id' => 63, 'name' => 'Vila Belmiro'],
        ['city_id' => 64, 'name' => 'Morumbi'],
        ['city_id' => 61, 'name' => 'Sao Januario'],
        ['city_id' => 62, 'name' => 'Barradao'],
        ['city_id' => 49, 'name' => 'Alfredo Jaconi'],
        ['city_id' => 50, 'name' => 'Heriberto Hulse'],
        ['city_id' => 54, 'name' => 'Antonio Accioly'],
        ['city_id' => 57, 'name' => 'Doutor Jorge Ismael de Biasi'],
        ['city_id' => 56, 'name' => 'Campos Maia'],
        ['city_id' => 59, 'name' => 'Ilha do Retiro'],
        ['city_id' => 54, 'name' => 'Onesio Brasileiro Alvarenga'],
        ['city_id' => 55, 'name' => 'Rei Pele'],
        ['city_id' => 48, 'name' => 'Brinco de Ouro'],
        ['city_id' => 53, 'name' => 'Castelao'],
        ['city_id' => 60, 'name' => 'Santa Cruz'],
        ['city_id' => 76, 'name' => 'Emirates Stadium'],
        ['city_id' => 65, 'name' => 'Villa Park'],
        ['city_id' => 66, 'name' => 'Dean Court'],
        ['city_id' => 76, 'name' => 'Brentford Community Stadium'],
        ['city_id' => 67, 'name' => 'Falmer Stadium'],
        ['city_id' => 69, 'name' => 'Turf Moor'],
        ['city_id' => 76, 'name' => 'Stamford Bridge'],
        ['city_id' => 76, 'name' => 'Selhurst Park'],
        ['city_id' => 75, 'name' => 'Goodison Park'],
        ['city_id' => 76, 'name' => 'Craven Cottage'],
        ['city_id' => 75, 'name' => 'Anfield'],
        ['city_id' => 77, 'name' => 'Kenilworth Road'],
        ['city_id' => 78, 'name' => 'City of Manchester Stadium'],
        ['city_id' => 78, 'name' => 'Old Trafford'],
        ['city_id' => 80, 'name' => 'St James Park'],
        ['city_id' => 86, 'name' => 'City Ground'],
        ['city_id' => 82, 'name' => 'Bramall Lane'],
        ['city_id' => 76, 'name' => 'Tottenham Hotspur Stadium'],
        ['city_id' => 76, 'name' => 'London Stadium'],
        ['city_id' => 88, 'name' => 'Molineux Stadium'],
        ['city_id' => 74, 'name' => 'King Power Stadium'],
        ['city_id' => 72, 'name' => 'Portman Road'],
        ['city_id' => 83, 'name' => 'St Mary\'s Stadium'],
        ['city_id' => 73, 'name' => 'Elland Road'],
        ['city_id' => 87, 'name' => 'The Hawthorns'],
        ['city_id' => 84, 'name' => 'Stadium of Light'],
        ['city_id' => 71, 'name' => 'MKM Stadium'],
        ['city_id' => 70, 'name' => 'Coventry Building Society Arena'],
        ['city_id' => 81, 'name' => 'Carrow Road'],
        ['city_id' => 85, 'name' => 'Vicarage Road'],
        ['city_id' => 68, 'name' => 'Ashton Gate Stadium'],
        ['city_id' => 79, 'name' => 'Riverside Stadium'],
        ['city_id' => 94, 'name' => 'Stade Francis-Le Ble'],
        ['city_id' => 96, 'name' => 'Stade Gabriel Montpied'],
        ['city_id' => 101, 'name' => 'Stade Oceane'],
        ['city_id' => 102, 'name' => 'Stade Bollaert-Delelis'],
        ['city_id' => 103, 'name' => 'Decathlon Arena Pierre Mauroy Stadium'],
        ['city_id' => 105, 'name' => 'Stade du Moustoir'],
        ['city_id' => 106, 'name' => 'Groupama Stadium'],
        ['city_id' => 107, 'name' => 'Orange Velodrome'],
        ['city_id' => 104, 'name' => 'Stade Saint-Symphorien'],
        ['city_id' => 108, 'name' => 'Stade Louis II'],
        ['city_id' => 109, 'name' => 'Stade de la Mosson'],
        ['city_id' => 110, 'name' => 'Stade de la Beaujoire'],
        ['city_id' => 111, 'name' => 'Allianz Riviera'],
        ['city_id' => 112, 'name' => 'Parc des Princes'],
        ['city_id' => 114, 'name' => 'Stade Auguste Delaune'],
        ['city_id' => 115, 'name' => 'Roazhon Park'],
        ['city_id' => 118, 'name' => 'Stade de la Meinau'],
        ['city_id' => 119, 'name' => 'Stadium Municipal'],
        ['city_id' => 89, 'name' => 'Stade Francois Coty'],
        ['city_id' => 90, 'name' => 'Stade de la Licorne'],
        ['city_id' => 91, 'name' => 'Stade Raymond Kopa'],
        ['city_id' => 92, 'name' => 'Stade de l\'Abbe-Deschamps'],
        ['city_id' => 93, 'name' => 'Matmut Atlantique'],
        ['city_id' => 95, 'name' => 'Stade Michel d\'Ornano'],
        ['city_id' => 97, 'name' => 'Stade Francis-Le Ble'],
        ['city_id' => 98, 'name' => 'Stade des Alpes'],
        ['city_id' => 99, 'name' => 'Stade de Roudourou'],
        ['city_id' => 100, 'name' => 'Stade Francis Le Basser'],
        ['city_id' => 112, 'name' => 'Stade Sebastien Charlety'],
        ['city_id' => 113, 'name' => 'Nouste Camp'],
        ['city_id' => 116, 'name' => 'Stade Paul-Lignon'],
        ['city_id' => 117, 'name' => 'Stade Geoffroy-Guichard'],
        ['city_id' => 120, 'name' => 'WWK Arena'],
        ['city_id' => 121, 'name' => 'Stadion An der Alten Försterei'],
        ['city_id' => 122, 'name' => 'Vonovia Ruhrstadion'],
        ['city_id' => 123, 'name' => 'Wohninvest Weserstadion'],
        ['city_id' => 125, 'name' => 'Merck-Stadion am Bollenfalltor'],
        ['city_id' => 126, 'name' => 'Signal Iduna Park'],
        ['city_id' => 128, 'name' => 'Deutsche Bank Park'],
        ['city_id' => 129, 'name' => 'Europa-Park Stadion'],
        ['city_id' => 134, 'name' => 'Voith-Arena'],
        ['city_id' => 145, 'name' => 'PreZero Arena'],
        ['city_id' => 124, 'name' => 'RheinEnergieStadion'],
        ['city_id' => 137, 'name' => 'Red Bull Arena'],
        ['city_id' => 138, 'name' => 'BayArena'],
        ['city_id' => 140, 'name' => 'Mewa Arena'],
        ['city_id' => 141, 'name' => 'Borussia-Park'],
        ['city_id' => 142, 'name' => 'Allianz Arena'],
        ['city_id' => 147, 'name' => 'MHPArena'],
        ['city_id' => 149, 'name' => 'Volkswagen Arena'],
        ['city_id' => 121, 'name' => 'Olympiastadion'],
        ['city_id' => 127, 'name' => 'Merkur Spiel-Arena'],
        ['city_id' => 146, 'name' => 'Waldstadion an der Kaiserlinde'],
        ['city_id' => 130, 'name' => 'Sportpark Ronhof Thomas Sommer'],
        ['city_id' => 132, 'name' => 'Volksparkstadion'],
        ['city_id' => 133, 'name' => 'Heinz von Heiden Arena'],
        ['city_id' => 135, 'name' => 'BBBank Wildpark'],
        ['city_id' => 136, 'name' => 'Holstein-Stadion'],
        ['city_id' => 139, 'name' => 'MDCC-Arena'],
        ['city_id' => 143, 'name' => 'Max-Morlock-Stadion'],
        ['city_id' => 144, 'name' => 'Home Deluxe Arena'],
        ['city_id' => 131, 'name' => 'Veltins-Arena'],
        ['city_id' => 132, 'name' => 'Millerntor-Stadion'],
        ['city_id' => 148, 'name' => 'BRITA-Arena'],
        ['city_id' => 151, 'name' => 'Stadio Atleti Azzurri d\'Italia'],
        ['city_id' => 152, 'name' => 'Stadio Renato Dall\'Ara'],
        ['city_id' => 155, 'name' => 'Unipol Domus'],
        ['city_id' => 160, 'name' => 'Stadio Carlo Castellani'],
        ['city_id' => 161, 'name' => 'Stadio Artemio Franchi'],
        ['city_id' => 162, 'name' => 'Stadio Benito Stirpe'],
        ['city_id' => 163, 'name' => 'Stadio Luigi Ferraris'],
        ['city_id' => 177, 'name' => 'Stadio Marcantonio Bentegodi'],
        ['city_id' => 165, 'name' => 'San Siro'],
        ['city_id' => 174, 'name' => 'Juventus Stadium'],
        ['city_id' => 171, 'name' => 'Stadio Olimpico'],
        ['city_id' => 164, 'name' => 'Stadio Via del mare'],
        ['city_id' => 165, 'name' => 'San Siro'],
        ['city_id' => 167, 'name' => 'Stadio Brianteo'],
        ['city_id' => 168, 'name' => 'Stadio Diego Armando Maradona'],
        ['city_id' => 171, 'name' => 'Stadio Olimpico'],
        ['city_id' => 172, 'name' => 'Stadio Arechi'],
        ['city_id' => 173, 'name' => 'Mapei Stadium'],
        ['city_id' => 174, 'name' => 'Stadio Olimpico Grande Torino'],
        ['city_id' => 175, 'name' => 'Stadio Friuli'],
        ['city_id' => 150, 'name' => 'Stadio San Nicola'],
        ['city_id' => 154, 'name' => 'Stadio Mario Rigamonti'],
        ['city_id' => 156, 'name' => 'Stadio Nicola Ceravolo'],
        ['city_id' => 157, 'name' => 'Stadio Pier Cesare Tombolato'],
        ['city_id' => 158, 'name' => 'Stadio Giuseppe Sinigaglia'],
        ['city_id' => 159, 'name' => 'Stadio Giovanni Zini'],
        ['city_id' => 166, 'name' => 'Stadio Alberto Braglia'],
        ['city_id' => 169, 'name' => 'Stadio Renzo Barbera'],
        ['city_id' => 170, 'name' => 'Stadio Ennio Tardini'],
        ['city_id' => 163, 'name' => 'Stadio Luigi Ferraris'],
        ['city_id' => 153, 'name' => 'Stadio Druso'],
        ['city_id' => 176, 'name' => 'Stadio Pier Luigi Penzo'],
        ['city_id' => 181, 'name' => 'Johan Cruijff Arena'],
        ['city_id' => 180, 'name' => 'Yanmar Stadion'],
        ['city_id' => 178, 'name' => 'AFAS Stadion'],
        ['city_id' => 198, 'name' => 'Van Donge & De Roo Stadion'],
        ['city_id' => 198, 'name' => 'De Kuip'],
        ['city_id' => 199, 'name' => 'Fortuna Sittard Stadion'],
        ['city_id' => 184, 'name' => 'De Adelaarshorst'],
        ['city_id' => 191, 'name' => 'Abe Lenstra Stadion'],
        ['city_id' => 179, 'name' => 'Erve Asito'],
        ['city_id' => 197, 'name' => 'Goffertstadion'],
        ['city_id' => 206, 'name' => 'MAC3PARK Stadion'],
        ['city_id' => 187, 'name' => 'Philips Stadion'],
        ['city_id' => 205, 'name' => 'Mandemakers Stadion'],
        ['city_id' => 198, 'name' => 'Spartastadion Het Kasteel'],
        ['city_id' => 189, 'name' => 'De Grolsch Veste'],
        ['city_id' => 202, 'name' => 'Stadion Galgenwaard'],
        ['city_id' => 182, 'name' => 'GelreDome'],
        ['city_id' => 204, 'name' => 'Kras Stadion'],
        ['city_id' => 200, 'name' => 'Bingoal Stadion'],
        ['city_id' => 195, 'name' => 'Cambuurstadion'],
        ['city_id' => 186, 'name' => 'Matchoholic Stadion'],
        ['city_id' => 187, 'name' => 'Jan Louwers Stadion'],
        ['city_id' => 188, 'name' => 'De Oude Meerdijk'],
        ['city_id' => 185, 'name' => 'Stadion De Vijverberg'],
        ['city_id' => 190, 'name' => 'Euroborg'],
        ['city_id' => 192, 'name' => 'GS Staalwerken Stadion'],
        ['city_id' => 193, 'name' => 'Stadion De Vliert'],
        ['city_id' => 196, 'name' => 'Stadion De Geusselt'],
        ['city_id' => 183, 'name' => 'Rat Verlegh Stadion'],
        ['city_id' => 194, 'name' => 'Parkstad Limburg Stadion'],
        ['city_id' => 203, 'name' => 'Covebo Stadion - De Koel'],
        ['city_id' => 201, 'name' => 'Koning Willem II Stadion'],
        ['city_id' => 208, 'name' => 'Estadio Municipal de Arouca'],
        ['city_id' => 217, 'name' => 'Estadio da Luz'],
        ['city_id' => 224, 'name' => 'Estadio do Bessa'],
        ['city_id' => 210, 'name' => 'Estadio Municipal de Braga'],
        ['city_id' => 217, 'name' => 'Estadio Municipal de Rio Maior'],
        ['city_id' => 211, 'name' => 'Estadio Municipal'],
        ['city_id' => 212, 'name' => 'Estadio Antonio Coimbra da Mota'],
        ['city_id' => 207, 'name' => 'Estadio Jose Gomes'],
        ['city_id' => 231, 'name' => 'Estadio Municipal 22 de Junho'],
        ['city_id' => 213, 'name' => 'Estadio de Sao Luis'],
        ['city_id' => 209, 'name' => 'Estadio Cidade de Barcelos'],
        ['city_id' => 219, 'name' => 'Parque de Jogos Comendador'],
        ['city_id' => 223, 'name' => 'Estadio Municipal de Portimao'],
        ['city_id' => 224, 'name' => 'Estadio do Dragao'],
        ['city_id' => 230, 'name' => 'Estadio dos Arcos'],
        ['city_id' => 217, 'name' => 'Estadio Jose Alvalade'],
        ['city_id' => 215, 'name' => 'Estadio D. Afonso Henriques'],
        ['city_id' => 234, 'name' => 'Estadio do FC Vizela'],
        ['city_id' => 233, 'name' => 'Estadio do Fontelo'],
        ['city_id' => 229, 'name' => 'Estadio do CD Aves'],
        ['city_id' => 226, 'name' => 'Benfica Campus'],
        ['city_id' => 225, 'name' => 'Estadio Marcolino de Castro'],
        ['city_id' => 218, 'name' => 'Estadio Municipal de Mafra'],
        ['city_id' => 214, 'name' => 'Estadio do Maritimo'],
        ['city_id' => 214, 'name' => 'Estadio da Madeira'],
        ['city_id' => 220, 'name' => 'Estadio Carlos Osorio'],
        ['city_id' => 221, 'name' => 'Estadio Capital do Movel'],
        ['city_id' => 232, 'name' => 'Estadio Municipal Jorge Sampaio'],
        ['city_id' => 222, 'name' => 'Estadio de Sao Miguel'],
        ['city_id' => 227, 'name' => 'Estadio Joao Cardoso'],
        ['city_id' => 228, 'name' => 'Estadio Manuel Marques'],
        ['city_id' => 216, 'name' => 'Estadio Dr. Magalhaes Pessoa'],
        ['city_id' => 262, 'name' => 'Mendizorroza'],
        ['city_id' => 235, 'name' => 'Power Horse Stadium'],
        ['city_id' => 237, 'name' => 'San Mames'],
        ['city_id' => 250, 'name' => 'Civitas Metropolitano'],
        ['city_id' => 236, 'name' => 'Estadi Olimpic Lluis Companys'],
        ['city_id' => 239, 'name' => 'Nuevo Mirandilla'],
        ['city_id' => 260, 'name' => 'ABANCA Balaidos'],
        ['city_id' => 244, 'name' => 'Coliseum'],
        ['city_id' => 246, 'name' => 'Montilivi'],
        ['city_id' => 247, 'name' => 'Nuevo Los Carmenes'],
        ['city_id' => 248, 'name' => 'Gran Canaria'],
        ['city_id' => 252, 'name' => 'Mallorca Son Moix'],
        ['city_id' => 253, 'name' => 'El Sadar'],
        ['city_id' => 250, 'name' => 'Vallecas'],
        ['city_id' => 257, 'name' => 'Benito Villamarin'],
        ['city_id' => 250, 'name' => 'Santiago Bernabeu'],
        ['city_id' => 254, 'name' => 'Reale Arena'],
        ['city_id' => 257, 'name' => 'Ramon Sanchez-Pizjuan'],
        ['city_id' => 258, 'name' => 'Mestalla'],
        ['city_id' => 261, 'name' => 'Estadio de la Ceramica'],
        ['city_id' => 238, 'name' => 'Estadio Municipal El Plantio'],
        ['city_id' => 241, 'name' => 'Estadio Municipal de Ipurua'],
        ['city_id' => 242, 'name' => 'Estadio Martinez Valero'],
        ['city_id' => 240, 'name' => 'Stage Front Stadium'],
        ['city_id' => 249, 'name' => 'Butarque'],
        ['city_id' => 258, 'name' => 'Ciutat de Valencia'],
        ['city_id' => 251, 'name' => 'Carlos Tartiere'],
        ['city_id' => 243, 'name' => 'A Malata'],
        ['city_id' => 256, 'name' => 'El Sardinero'],
        ['city_id' => 245, 'name' => 'El Molinon'],
        ['city_id' => 255, 'name' => 'Heliodoro Rodriguez Lopez'],
        ['city_id' => 259, 'name' => 'Jose Zorrilla'],
    ];

    /**
     * @return void
     */
    public function run(): void
    {
        foreach ($this->list as $item) {
            Stadium::create(['city_id' => $item['city_id'], 'name' => $item['name']]);
        }
    }
}
